title: UpTail
author:
  name: Joe Bloggs
  email: 'joe@test.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
    
# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Solutions
    url: '#solutions'
  - title: Services
    url: '#services'
  # - title: Training
  #   url: '#training'
  - title: Contact us
    url: '#contact'         
  - title: Blog
    url: '/blog'         

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/18769166/admin/
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

quicklinks:
  - title: Home
    url: '#'
  - title: Solutions
    url: '#solutions'
  - title: Services
    url: '#services'
  - title: Contact Us 
    url: '#contact'
  - title: Blog 
    url: 'blog'

brand:
 - Up
 - Tail